/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardManageRouteImport } from './routes/dashboard.manage'
import { Route as DashboardBlacklistRouteImport } from './routes/dashboard.blacklist'
import { Route as ApiPublicWebhookOrdersRouteImport } from './routes/api/public/webhook.orders'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManageRoute = DashboardManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlacklistRoute = DashboardBlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicWebhookOrdersRoute = ApiPublicWebhookOrdersRouteImport.update({
  id: '/api/public/webhook/orders',
  path: '/api/public/webhook/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/private': typeof PrivateRoute
  '/profit': typeof ProfitRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/dashboard/blacklist': typeof DashboardBlacklistRoute
  '/dashboard/manage': typeof DashboardManageRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/webhook/orders': typeof ApiPublicWebhookOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/private': typeof PrivateRoute
  '/profit': typeof ProfitRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/dashboard/blacklist': typeof DashboardBlacklistRoute
  '/dashboard/manage': typeof DashboardManageRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/webhook/orders': typeof ApiPublicWebhookOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/private': typeof PrivateRoute
  '/profit': typeof ProfitRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/dashboard/blacklist': typeof DashboardBlacklistRoute
  '/dashboard/manage': typeof DashboardManageRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/webhook/orders': typeof ApiPublicWebhookOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/private'
    | '/profit'
    | '/settings'
    | '/signup'
    | '/support'
    | '/dashboard/blacklist'
    | '/dashboard/manage'
    | '/dashboard/reports'
    | '/dashboard/'
    | '/api/public/webhook/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/private'
    | '/profit'
    | '/settings'
    | '/signup'
    | '/support'
    | '/dashboard/blacklist'
    | '/dashboard/manage'
    | '/dashboard/reports'
    | '/dashboard'
    | '/api/public/webhook/orders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/private'
    | '/profit'
    | '/settings'
    | '/signup'
    | '/support'
    | '/dashboard/blacklist'
    | '/dashboard/manage'
    | '/dashboard/reports'
    | '/dashboard/'
    | '/api/public/webhook/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivateRoute: typeof PrivateRoute
  ProfitRoute: typeof ProfitRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  ApiPublicWebhookOrdersRoute: typeof ApiPublicWebhookOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/manage': {
      id: '/dashboard/manage'
      path: '/manage'
      fullPath: '/dashboard/manage'
      preLoaderRoute: typeof DashboardManageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blacklist': {
      id: '/dashboard/blacklist'
      path: '/blacklist'
      fullPath: '/dashboard/blacklist'
      preLoaderRoute: typeof DashboardBlacklistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/webhook/orders': {
      id: '/api/public/webhook/orders'
      path: '/api/public/webhook/orders'
      fullPath: '/api/public/webhook/orders'
      preLoaderRoute: typeof ApiPublicWebhookOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBlacklistRoute: typeof DashboardBlacklistRoute
  DashboardManageRoute: typeof DashboardManageRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBlacklistRoute: DashboardBlacklistRoute,
  DashboardManageRoute: DashboardManageRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivateRoute: PrivateRoute,
  ProfitRoute: ProfitRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  ApiPublicWebhookOrdersRoute: ApiPublicWebhookOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
